{% set name = "r-localignr" %}
{% set version = "0.1.0" %}
{% set build = 1 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ..

build:
  number: {{ build }}
  noarch: generic
  script: R CMD INSTALL . --no-multiarch

requirements:
  host:
    - r-base >=4.2.0
    - r-shiny
    - r-rappdirs
    - r-shinythemes
    - r-dt
    - r-shinyfiles
    - r-shinybusy
    - r-xml
    - r-plyr
    - r-dplyr
    - r-yaml
    - r-processx
    - r-digest
    - r-htmltools
    - r-htmlwidgets
  run:
    - r-base >=4.2.0
    - r-shiny
    - r-rappdirs
    - r-shinythemes
    - r-dt
    - r-shinyfiles
    - r-shinybusy
    - r-xml
    - r-plyr
    - r-dplyr
    - r-yaml
    - r-processx
    - r-digest
    - r-htmltools
    - r-htmlwidgets
    - blast >=2.12.0
    - diamond >=2.0.0

test:
  commands:
    - $R -e "library('LocAlignR')"

about:
  home: https://github.com/franciscolobo/LocAlignR
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: 'Local alignment visualization and analysis tool'

extra:
  recipe-maintainers:
    - franciscolobo
